/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedImoveisIndexRouteImport } from './routes/_authenticated/imoveis.index'
import { Route as AuthenticatedDocumentosIndexRouteImport } from './routes/_authenticated/documentos.index'
import { Route as AuthenticatedImoveisNovoRouteImport } from './routes/_authenticated/imoveis.novo'
import { Route as AuthenticatedImoveisIdRouteImport } from './routes/_authenticated/imoveis.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImoveisIndexRoute =
  AuthenticatedImoveisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedDocumentosIndexRoute =
  AuthenticatedDocumentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedImoveisNovoRoute =
  AuthenticatedImoveisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedImoveisIdRoute = AuthenticatedImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/imoveis/': typeof AuthenticatedImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/documentos': typeof AuthenticatedDocumentosIndexRoute
  '/imoveis': typeof AuthenticatedImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/_authenticated/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/_authenticated/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/_authenticated/imoveis/': typeof AuthenticatedImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/documentos'
    | '/imoveis'
    | '/api/chat'
    | '/imoveis/$id'
    | '/imoveis/novo'
    | '/documentos/'
    | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api/chat'
    | '/'
    | '/imoveis/$id'
    | '/imoveis/novo'
    | '/documentos'
    | '/imoveis'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/documentos'
    | '/_authenticated/imoveis'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/imoveis/$id'
    | '/_authenticated/imoveis/novo'
    | '/_authenticated/documentos/'
    | '/_authenticated/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imoveis/': {
      id: '/_authenticated/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AuthenticatedImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/documentos/': {
      id: '/_authenticated/documentos/'
      path: '/'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthenticatedDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/imoveis/novo': {
      id: '/_authenticated/imoveis/novo'
      path: '/novo'
      fullPath: '/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/imoveis/$id': {
      id: '/_authenticated/imoveis/$id'
      path: '/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof AuthenticatedImoveisIdRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
  }
}

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosIndexRoute: typeof AuthenticatedDocumentosIndexRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosIndexRoute: AuthenticatedDocumentosIndexRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedImoveisRouteChildren {
  AuthenticatedImoveisIdRoute: typeof AuthenticatedImoveisIdRoute
  AuthenticatedImoveisNovoRoute: typeof AuthenticatedImoveisNovoRoute
  AuthenticatedImoveisIndexRoute: typeof AuthenticatedImoveisIndexRoute
}

const AuthenticatedImoveisRouteChildren: AuthenticatedImoveisRouteChildren = {
  AuthenticatedImoveisIdRoute: AuthenticatedImoveisIdRoute,
  AuthenticatedImoveisNovoRoute: AuthenticatedImoveisNovoRoute,
  AuthenticatedImoveisIndexRoute: AuthenticatedImoveisIndexRoute,
}

const AuthenticatedImoveisRouteWithChildren =
  AuthenticatedImoveisRoute._addFileChildren(AuthenticatedImoveisRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
